---
components:
  - name: backend
    type: service
    image: golang:1.22
    port: 8080
    build:
      steps:
        - directory: /build
        - copy: src/*
          destination: /build/
        - run: go build -o /app/backend ./...
    runtime:
      command: '/app/backend'
      variables:
        MYSQL_HOST:
          $resources: Database.host
        MYSQL_USER:
          $resources: Database.username
        MYSQL_PASSWORD:
          $resources: Database.password
        MYSQL_DBNAME:
          $resources: Database.database
      resources:
        - Database

resources:
  - name: Database
    type: mysql

routes:
  - pattern: /**
    target:
      component: backend
